package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/drGrove/zkret-santa/internal/output"
	"github.com/drGrove/zkret-santa/internal/parser"
	"github.com/drGrove/zkret-santa/pkg/selector"
)

const (
	ExitSuccess     = 0
	ExitUserError   = 1
	ExitSystemError = 2
)

const (
  BinaryName = "zkret-santa"
)

func main() {
	os.Exit(run())
}

func run() int {
	// Define command-line flags
	seedFlag := flag.String("seed", "", "256-bit seed as 64-character hex string (optional)")
	formatFlag := flag.String("format", "text", "Output format: text or json")
	flag.Parse()

	// Get the file path from positional argument
	args := flag.Args()

	// For zkSNARK operations, we may not need a participants file
	// Check if we're doing a zkSNARK-only operation first
	var names []string
	var filePath string

	if len(args) == 1 {
		filePath = args[0]

		// Validate format flag
		if *formatFlag != "text" && *formatFlag != "json" {
			fmt.Fprintf(os.Stderr, "Error: invalid format %q, must be 'text' or 'json'\n", *formatFlag)
			return ExitUserError
		}

		// Parse the participants file
		var err error
		names, err = parser.ParseFile(filePath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
			return ExitUserError
		}
	} else if len(args) != 0 {
		fmt.Fprintln(os.Stderr, "Usage: ", BinaryName, " [OPTIONS] <participants-file>")
		fmt.Fprintln(os.Stderr, "")
		fmt.Fprintln(os.Stderr, "Options:")
		fmt.Fprintln(os.Stderr, "  --seed         256-bit seed as 64-character hex string (default: random)")
		fmt.Fprintln(os.Stderr, "  --format       Output format: text or json (default: text)")
		printZKSNARKUsage()
		return ExitUserError
	}

	// Get or generate seed
	var seed []byte
	var seedWasAutoGenerated bool
	var err error
	if *seedFlag != "" {
		seed, err = selector.ParseSeed(*seedFlag)
		seedWasAutoGenerated = false
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
			return ExitUserError
		}
	} else {
		seed, err = selector.GenerateSeed()
		seedWasAutoGenerated = true
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
			return ExitSystemError
		}
	}

	// Handle zkSNARK flags if enabled (compile-time feature)
	handled, exitCode := handleZKSNARKFlags(seed, seedWasAutoGenerated, filePath)
	if handled {
		return exitCode
	}

	// If we get here, we need a participants file to generate assignments
	if len(names) == 0 {
		fmt.Fprintln(os.Stderr, "Error: participants file required for assignment generation")
		fmt.Fprintln(os.Stderr, "Usage: ", BinaryName, " [OPTIONS] <participants-file>")
		return ExitUserError
	}

	// Generate assignments
	assignments, err := selector.GenerateAssignments(names, seed)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		return ExitUserError
	}

	// Format and output results
	var result string
	if *formatFlag == "json" {
		result, err = output.FormatJSON(assignments)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
			return ExitSystemError
		}
	} else {
		result = output.FormatText(assignments, names)
	}

	fmt.Println(result)
	return ExitSuccess
}
