//go:build zksnark

package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"os"

	"github.com/drGrove/zkret-santa/pkg/zkproof"
)

var (
	// zkSNARK-specific flags
	proveFlag      = flag.Bool("prove", false, "Generate zkSNARK proof of seed knowledge")
	verifyFlag     = flag.String("verify", "", "Verify zkSNARK proof from JSON file")
	commitmentFlag = flag.Bool("commitment", false, "Output only the seed commitment (SHA-256 hash)")
	proofFileFlag  = flag.String("proof-file", "", "File to save/load proof data (default: stdout for save, required for verify)")
)

// printZKSNARKUsage prints zkSNARK-related usage information
func printZKSNARKUsage() {
	fmt.Fprintln(os.Stderr, "")
	fmt.Fprintln(os.Stderr, "zkSNARK Options (build with -tags zksnark):")
	fmt.Fprintln(os.Stderr, "  --prove        Generate zkSNARK proof of seed knowledge")
	fmt.Fprintln(os.Stderr, "  --verify FILE  Verify zkSNARK proof from JSON file")
	fmt.Fprintln(os.Stderr, "  --commitment   Output only the seed commitment (SHA-256)")
	fmt.Fprintln(os.Stderr, "  --proof-file   File to save/load proof data")
}

// handleZKSNARKFlags processes zkSNARK-specific flags and returns true if handled
func handleZKSNARKFlags(seed []byte, seedWasAutoGenerated bool, participantsFilePath string) (bool, int) {
	// Handle commitment-only mode
	if *commitmentFlag {
		commitment, err := zkproof.ComputeCommitment(seed)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error computing commitment: %v\n", err)
			return true, ExitSystemError
		}
		fmt.Printf("Seed Commitment (SHA-256): %s\n", hex.EncodeToString(commitment))
		return true, ExitSuccess
	}

	// Handle proof generation
	if *proveFlag {
		return handleProofGeneration(seed, seedWasAutoGenerated, participantsFilePath)
	}

	// Handle proof verification
	if *verifyFlag != "" {
		return handleProofVerification(*verifyFlag)
	}

	// No zkSNARK flags were used
	return false, ExitSuccess
}

// handleProofGeneration generates and outputs a zkSNARK proof
func handleProofGeneration(seed []byte, seedWasAutoGenerated bool, participantsFilePath string) (bool, int) {
	fmt.Fprintln(os.Stdout, "Generating zkSNARK proof...")
	fmt.Fprintln(os.Stdout, "Step 1/3: Running trusted setup...")

	// Run the trusted setup
	keys, err := zkproof.Setup()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error during setup: %v\n", err)
		return true, ExitSystemError
	}

	fmt.Fprintln(os.Stdout, "Step 2/3: Generating proof...")

	// Generate the proof
	proofData, err := zkproof.GenerateProof(seed, keys)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating proof: %v\n", err)
		return true, ExitSystemError
	}

	fmt.Fprintln(os.Stdout, "Step 3/3: Serializing proof...")

	// Convert to serializable format
	serializable, err := proofData.ToSerializable()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error serializing proof: %v\n", err)
		return true, ExitSystemError
	}

	// Encode as JSON
	jsonBytes, err := json.MarshalIndent(serializable, "", "  ")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error encoding JSON: %v\n", err)
		return true, ExitSystemError
	}

	// Output to file or stdout
	if *proofFileFlag != "" {
		err = os.WriteFile(*proofFileFlag, jsonBytes, 0644)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error writing proof file: %v\n", err)
			return true, ExitSystemError
		}
		fmt.Fprintf(os.Stdout, "Proof saved to: %s\n", *proofFileFlag)
		fmt.Fprintf(os.Stdout, "Commitment: %s\n", serializable.Commitment)
	} else {
		fmt.Println(string(jsonBytes))
	}

	// Save seed file if conditions are met
	if seedWasAutoGenerated && participantsFilePath != "" {
		if err := saveSeedFile(seed, participantsFilePath); err != nil {
			fmt.Fprintf(os.Stderr, "Warning: failed to save seed file: %v\n", err)
			// Don't fail the operation, just warn
		}
	}

	fmt.Fprintln(os.Stdout, "✓ Proof generation complete")
	return true, ExitSuccess
}

// handleProofVerification verifies a zkSNARK proof from a file
func handleProofVerification(proofFile string) (bool, int) {
	fmt.Fprintf(os.Stdout, "Verifying zkSNARK proof from: %s\n", proofFile)

	// Read proof file
	jsonBytes, err := os.ReadFile(proofFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading proof file: %v\n", err)
		return true, ExitSystemError
	}

	// Deserialize proof
	var serializable zkproof.SerializableProof
	err = json.Unmarshal(jsonBytes, &serializable)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing proof JSON: %v\n", err)
		return true, ExitSystemError
	}

	// Convert back to ProofData
	proofData, err := zkproof.FromSerializable(&serializable)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error deserializing proof: %v\n", err)
		return true, ExitSystemError
	}

	// Verify the proof
	valid, err := zkproof.VerifyProof(proofData)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error during verification: %v\n", err)
		return true, ExitSystemError
	}

	if valid {
		fmt.Println("✓ Proof is VALID")
		fmt.Printf("Commitment: %s\n", serializable.Commitment)
		return true, ExitSuccess
	} else {
		fmt.Println("✗ Proof is INVALID")
		return true, ExitUserError
	}
}

// saveSeedFile saves the seed to a file named <hash>.seed where hash is SHA-256 of participants file
func saveSeedFile(seed []byte, participantsFilePath string) error {
	// Read the participants file contents
	fileContents, err := os.ReadFile(participantsFilePath)
	if err != nil {
		return fmt.Errorf("cannot read participants file: %w", err)
	}

	// Compute SHA-256 hash of file contents
	hash := sha256.Sum256(fileContents)
	hashHex := hex.EncodeToString(hash[:])

	// Create seed filename
	seedFilename := hashHex + ".seed"

	// Encode seed as hex
	seedHex := hex.EncodeToString(seed)

	// Write seed to file
	err = os.WriteFile(seedFilename, []byte(seedHex), 0644)
	if err != nil {
		return fmt.Errorf("cannot write seed file: %w", err)
	}

	fmt.Fprintf(os.Stderr, "Seed saved to: %s\n", seedFilename)
	return nil
}
