//go:build !zksnark

package main

import (
	"fmt"
	"os"
)

// printZKSNARKUsage prints a message that zkSNARK support is not enabled
func printZKSNARKUsage() {
	fmt.Fprintln(os.Stderr, "")
	fmt.Fprintln(os.Stderr, "zkSNARK support not enabled in this build.")
	fmt.Fprintln(os.Stderr, "Rebuild with tag: zksnark")
}

// handleZKSNARKFlags is a stub when zksnark build tag is not enabled
// It always returns false to indicate no zkSNARK flags were handled
func handleZKSNARKFlags(seed []byte, seedWasAutoGenerated bool, participantsFilePath string) (bool, int) {
	return false, ExitSuccess
}
